file.choose()
reportes = read.csv("C:\\Bedu\\Proyecto tarjetas\\reportes_agua_hist.csv")
View(reportes)
names(reportes)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidyr)
head(reportes)
class(reportes)
dim(reportes)
(str(reportes))
summary(reportes)
